### PR TITLE
English articles improvements

### PR DESCRIPTION
**Pull request by xEdziu**
## I have tried to improve english grammar, to make the article more accessible for readers.

### CODE REVIEW

**Comment by kamiloox** [comment]
Thank you for tackling down on this, I appreciate 🙏
I will take a look at this in my free time

**Comment by xEdziu** [comment]
I also improved grammar in article about token on front end.
Great article tho!
Keep up the good work

**Comment by kamiloox** [comment]
You did great work @xEdziu . I haven't found any mistake for now (but we will see in the future ofc 😅). Anyway, thanks so much for fixing this!

**Comment by xEdziu** [comment]
I am always happy to help! ❤️

**Pull request merged**
